-- Baseline: the production schema of project ceacurlofmasyvhsoska as it actually was on
-- 2026-09-24, captured read-only with `supabase db dump --linked` (public schema; Supabase-managed
-- schemas excluded). This file DESCRIBES production; it was never applied to it. Production's
-- migration history must be told this version is already applied before the first
-- `supabase db push` — see docs/07-development-setup.md#database-migrations.
--
-- Deliberately a faithful copy, bugs included: it is the starting point every later migration
-- diffs against, so "fixing" anything here would make it lie about production. Known live defects
-- reproduced below on purpose (fixed by a later migration, not by editing this file):
--   * enforce_capacity_and_waitlist() and the "User Parties: User can update own registrations"
--     policy still compare status against the old French values ('Enregistré', 'En attente'),
--     which the CHECK constraint no longer allows.
--   * user_parties.status / payment_status still DEFAULT to 'Enregistré' / 'Impayé'.
--
-- The one hand-added statement is the on_auth_user_created trigger at the end: it lives on
-- auth.users, which the dump excludes, but it exists in production (verified via pg_trigger).
-- The only other edit to the dump output: several function bodies were stored in production with
-- CRLF line endings; they are normalized to LF here (no effect on behaviour).
--
-- Do not edit this file. Change the schema with a new migration: `supabase migration new <name>`.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER SCHEMA "public" OWNER TO "postgres";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE OR REPLACE FUNCTION "public"."admin_set_is_admin"("target_user_id" "uuid", "new_is_admin" boolean) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
DECLARE
    target_email TEXT;
BEGIN
    -- Ensure caller is admin
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Only administrators can change admin status';
    END IF;

    -- Prevent self-promotion/demotion
    IF target_user_id = auth.uid() THEN
        RAISE EXCEPTION 'Cannot change your own admin status';
    END IF;

    -- Fetch target email to protect root admin
    SELECT email INTO target_email
    FROM public.profiles
    WHERE id = target_user_id;

    -- Block demotion of root admin
    IF target_email = 'yulmixalabedaine@gmail.com' AND new_is_admin = FALSE THEN
        RAISE EXCEPTION 'Le compte administrateur racine ne peut pas être rétrogradé.';
    END IF;

    -- Update the profile
    UPDATE public.profiles
    SET is_admin = new_is_admin
    WHERE id = target_user_id;

    -- Ensure at least one admin remains (hardcoded root admin excluded)
    -- Root admin yulmixalabedaine@gmail.com is already protected by is_admin() function
END;
$$;

ALTER FUNCTION "public"."admin_set_is_admin"("target_user_id" "uuid", "new_is_admin" boolean) OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."enforce_capacity_and_waitlist"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
    v_event_id UUID;
    v_max_attendees INT;
    v_current_registered INT;
    v_is_waitlisted BOOLEAN;
BEGIN
    -- Determine event ID
    v_event_id := NEW.event_id;
    
    -- Get max attendees for the event
    SELECT max_attendees INTO v_max_attendees
    FROM public.events
    WHERE id = v_event_id;
    
    -- If max_attendees is NULL or 0, no capacity restriction
    IF v_max_attendees IS NULL OR v_max_attendees <= 0 THEN
        NEW.is_waitlisted := FALSE;
        RETURN NEW;
    END IF;
    
    -- Use advisory lock to serialize concurrent inserts for the same event
    -- This prevents race conditions where two parties check capacity simultaneously
    PERFORM pg_advisory_xact_lock(hashtext(v_event_id::text));
    
    -- Count total attendees from non-waitlisted, registered parties for this event
    -- Exclude the current party (if updating) and already waitlisted parties
    SELECT COALESCE(SUM(jsonb_array_length(up.attendees)), 0) INTO v_current_registered
    FROM public.user_parties up
    WHERE up.event_id = v_event_id
      AND up.is_waitlisted = FALSE
      AND up.status IN ('Enregistré', 'En attente')
      AND up.id != COALESCE(NEW.id, '00000000-0000-0000-0000-000000000000'::UUID);
    
    -- Add the attendees from the new/updated party
    v_current_registered := v_current_registered + jsonb_array_length(NEW.attendees);
    
    -- Determine waitlist status
    v_is_waitlisted := v_current_registered > v_max_attendees;
    
    -- Override client-provided is_waitlisted with server-calculated value
    NEW.is_waitlisted := v_is_waitlisted;
    
    RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."enforce_capacity_and_waitlist"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, is_admin)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
        (NEW.email = 'yulmixalabedaine@gmail.com')
    );
    RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."increment_edit_count"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    NEW.edit_count = OLD.edit_count + 1;
    NEW.last_edited_at = NOW();
    RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."increment_edit_count"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid()
        AND (is_admin = TRUE OR email = 'yulmixalabedaine@gmail.com')
    );
END;
$$;

ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."log_registration_edit"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
DECLARE
    changes_json JSONB := '{}'::JSONB;
BEGIN
    IF OLD.attendees IS DISTINCT FROM NEW.attendees THEN
        changes_json = jsonb_set(changes_json, '{attendees}', jsonb_build_object('old', OLD.attendees, 'new', NEW.attendees));
    END IF;
    IF OLD.counts IS DISTINCT FROM NEW.counts THEN
        changes_json = jsonb_set(changes_json, '{counts}', jsonb_build_object('old', OLD.counts, 'new', NEW.counts));
    END IF;
    IF OLD.logistics IS DISTINCT FROM NEW.logistics THEN
        changes_json = jsonb_set(changes_json, '{logistics}', jsonb_build_object('old', OLD.logistics, 'new', NEW.logistics));
    END IF;
    IF OLD.transport IS DISTINCT FROM NEW.transport THEN
        changes_json = jsonb_set(changes_json, '{transport}', jsonb_build_object('old', OLD.transport, 'new', NEW.transport));
    END IF;
    IF OLD.music_requests IS DISTINCT FROM NEW.music_requests THEN
        changes_json = jsonb_set(changes_json, '{music_requests}', jsonb_build_object('old', OLD.music_requests, 'new', NEW.music_requests));
    END IF;
    IF OLD.message_to_organizers IS DISTINCT FROM NEW.message_to_organizers THEN
        changes_json = jsonb_set(changes_json, '{message_to_organizers}', jsonb_build_object('old', OLD.message_to_organizers, 'new', NEW.message_to_organizers));
    END IF;
    IF OLD.confirmation_message IS DISTINCT FROM NEW.confirmation_message THEN
        changes_json = jsonb_set(changes_json, '{confirmation_message}', jsonb_build_object('old', OLD.confirmation_message, 'new', NEW.confirmation_message));
    END IF;
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        changes_json = jsonb_set(changes_json, '{status}', jsonb_build_object('old', OLD.status, 'new', NEW.status));
    END IF;
    IF OLD.calculated_amount_owed IS DISTINCT FROM NEW.calculated_amount_owed THEN
        changes_json = jsonb_set(changes_json, '{calculated_amount_owed}', jsonb_build_object('old', OLD.calculated_amount_owed, 'new', NEW.calculated_amount_owed));
    END IF;
    IF OLD.payment_status IS DISTINCT FROM NEW.payment_status THEN
        changes_json = jsonb_set(changes_json, '{payment_status}', jsonb_build_object('old', OLD.payment_status, 'new', NEW.payment_status));
    END IF;
    IF OLD.is_waitlisted IS DISTINCT FROM NEW.is_waitlisted THEN
        changes_json = jsonb_set(changes_json, '{is_waitlisted}', jsonb_build_object('old', OLD.is_waitlisted, 'new', NEW.is_waitlisted));
    END IF;
    IF OLD.admin_notes IS DISTINCT FROM NEW.admin_notes THEN
        changes_json = jsonb_set(changes_json, '{admin_notes}', jsonb_build_object('old', OLD.admin_notes, 'new', NEW.admin_notes));
    END IF;

    IF changes_json != '{}'::JSONB THEN
        INSERT INTO public.registration_edits (registration_id, edited_by, changes)
        VALUES (NEW.id, NEW.user_id, changes_json);
    END IF;

    RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."log_registration_edit"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."prevent_event_deletion"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    RAISE EXCEPTION 'Les événements ne peuvent pas être supprimés. Utilisez l''archivage à la place.';
END;
$$;

ALTER FUNCTION "public"."prevent_event_deletion"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."prevent_self_privilege_escalation"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    IF (NEW.id = auth.uid() AND OLD.is_admin IS DISTINCT FROM NEW.is_admin) THEN
        IF EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND is_admin = TRUE
        ) THEN
            RAISE EXCEPTION 'Les administrateurs ne peuvent pas modifier leur propre statut d''administrateur.';
        ELSE
            RAISE EXCEPTION 'Les utilisateurs ne peuvent pas s''attribuer eux-mêmes des privilèges d''administrateur.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."prevent_self_privilege_escalation"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."protect_root_admin"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    IF OLD.email = 'yulmixalabedaine@gmail.com' AND NEW.is_admin = FALSE THEN
        RAISE EXCEPTION 'Le compte administrateur racine ne peut pas être rétrogradé.';
    END IF;
    RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."protect_root_admin"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."update_attendee_counts"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
    counts JSONB := '{"adult_whole":0,"adult_main":0,"teen_whole":0,"teen_main":0,"kids":0}'::jsonb;
    attendee JSONB;
    tier_name TEXT;
BEGIN
    IF NEW.attendees IS NOT NULL AND jsonb_typeof(NEW.attendees) = 'array' THEN
        FOR attendee IN SELECT * FROM jsonb_array_elements(NEW.attendees)
        LOOP
            tier_name := CASE
                WHEN attendee->>'type' = 'Adult' AND attendee->>'participation' = 'Whole' THEN 'adult_whole'
                WHEN attendee->>'type' = 'Adult' THEN 'adult_main'
                WHEN attendee->>'type' = 'Teenager' AND attendee->>'participation' = 'Whole' THEN 'teen_whole'
                WHEN attendee->>'type' = 'Teenager' THEN 'teen_main'
                WHEN attendee->>'type' = 'Kid' THEN 'kids'
                ELSE NULL
            END;
            IF tier_name IS NOT NULL THEN
                counts := jsonb_set(
                    counts,
                    ARRAY[tier_name],
                    to_jsonb(COALESCE((counts->>tier_name)::int, 0) + 1)
                );
            END IF;
        END LOOP;
    END IF;

    NEW.counts := counts;
    RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."update_attendee_counts"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."app_feedback" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "content" "text" NOT NULL,
    "screenshot_url" "text",
    "is_resolved" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "resolved_at" timestamp with time zone
);

ALTER TABLE "public"."app_feedback" OWNER TO "postgres";

COMMENT ON TABLE "public"."app_feedback" IS 'User feedback and bug reports with resolution tracking';

CREATE TABLE IF NOT EXISTS "public"."events" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "theme" "text" NOT NULL,
    "description" "text",
    "venue_address" "text",
    "duration_days" integer DEFAULT 2,
    "points_of_contact" "text" DEFAULT 'Registration (Simon), Volunteering (Dave), Food/Special Activities (Melina / MC / Gary), Neighbors / Parking (Khaled), Pharma / First Aid / Bed Assignments (Mach)'::"text",
    "z_intent_months" integer DEFAULT 2,
    "x_reg_close_weeks" integer DEFAULT 1,
    "reg_start_date" "date" DEFAULT '2026-05-01'::"date",
    "status" "text" DEFAULT 'DRAFT'::"text",
    "is_active" boolean DEFAULT false,
    "is_reg_open" boolean DEFAULT false,
    "total_cost" numeric(10,2) DEFAULT 0.00,
    "cost_breakdown" "jsonb" DEFAULT '[]'::"jsonb",
    "expense_category" "text",
    "selling_price_whole_event" numeric(10,2) DEFAULT 0.00,
    "estimated_individual_cost_whole_event" numeric(10,2) DEFAULT 0.00,
    "max_attendees" integer DEFAULT 90,
    "external_links" "jsonb" DEFAULT '[]'::"jsonb",
    "instructions" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "events_expense_category_check" CHECK (("expense_category" = ANY (ARRAY['Chalet'::"text", 'Food'::"text", 'Music'::"text", 'Tech'::"text", 'Accessories'::"text"]))),
    CONSTRAINT "events_status_check" CHECK (("status" = ANY (ARRAY['DRAFT'::"text", 'ACTIVE'::"text", 'ARCHIVED'::"text"])))
);

ALTER TABLE "public"."events" OWNER TO "postgres";

COMMENT ON TABLE "public"."events" IS 'Event management with strict no-delete and single-active-event constraints';

COMMENT ON COLUMN "public"."events"."points_of_contact" IS 'Default contact points: Registration (Simon), Volunteering (Dave), Food/Special Activities (Melina / MC / Gary), Neighbors / Parking (Khaled), Pharma / First Aid / Bed Assignments (Mach)';

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "full_name" "text",
    "is_admin" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

COMMENT ON TABLE "public"."profiles" IS 'User profiles synchronized with Supabase auth.users table';

CREATE TABLE IF NOT EXISTS "public"."registration_edits" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "registration_id" "uuid" NOT NULL,
    "edited_at" timestamp with time zone DEFAULT "now"(),
    "edited_by" "uuid",
    "changes" "jsonb"
);

ALTER TABLE "public"."registration_edits" OWNER TO "postgres";

COMMENT ON TABLE "public"."registration_edits" IS 'Audit trail for registration edits';

CREATE TABLE IF NOT EXISTS "public"."user_parties" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "event_id" "uuid" NOT NULL,
    "attendees" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "counts" "jsonb" DEFAULT '{"kids": 0, "teen_main": 0, "adult_main": 0, "teen_whole": 0, "adult_whole": 0}'::"jsonb" NOT NULL,
    "logistics" "jsonb" DEFAULT '{"sleeping": {"pref": "", "reason": "", "assigned": ""}, "volunteering": [], "food_requests": {"notes": "", "requests": ""}}'::"jsonb" NOT NULL,
    "transport" "jsonb" DEFAULT '{"type": "None", "seats": 0, "arrival": "", "departure": ""}'::"jsonb" NOT NULL,
    "music_requests" "text",
    "message_to_organizers" "text",
    "confirmation_message" "text",
    "status" "text" DEFAULT 'Enregistré'::"text",
    "calculated_amount_owed" numeric(10,2) DEFAULT 0.00,
    "payment_status" "text" DEFAULT 'Impayé'::"text",
    "is_waitlisted" boolean DEFAULT false,
    "admin_notes" "text",
    "last_edited_at" timestamp with time zone DEFAULT "now"(),
    "edit_count" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "user_parties_payment_status_check" CHECK (("payment_status" = ANY (ARRAY['unpaid'::"text", 'paid'::"text"]))),
    CONSTRAINT "user_parties_status_check" CHECK (("status" = ANY (ARRAY['registered'::"text", 'pending'::"text", 'cancelled'::"text"])))
);

ALTER TABLE "public"."user_parties" OWNER TO "postgres";

COMMENT ON TABLE "public"."user_parties" IS 'Event registrations with attendee tracking and payment status';

COMMENT ON COLUMN "public"."user_parties"."attendees" IS 'Array of objects: [{"name": "...", "tier": "adult_whole" | "adult_main" | "teen_whole" | "teen_main" | "kids", "is_new_member": boolean}]';

COMMENT ON COLUMN "public"."user_parties"."counts" IS 'Auto-computed from attendees on insert/update';

COMMENT ON COLUMN "public"."user_parties"."admin_notes" IS 'Private notes reserved for organizers only';

COMMENT ON COLUMN "public"."user_parties"."last_edited_at" IS 'Timestamp of last edit to registration';

COMMENT ON COLUMN "public"."user_parties"."edit_count" IS 'Number of times registration has been edited';

CREATE OR REPLACE VIEW "public"."user_event_history" WITH ("security_invoker"='true') AS
 SELECT "p"."id" AS "user_id",
    "p"."email",
    "p"."full_name",
    "up"."id" AS "party_id",
    "e"."id" AS "event_id",
    "e"."theme" AS "event_theme",
    "e"."reg_start_date",
    "up"."status" AS "registration_status",
    "up"."calculated_amount_owed",
    "up"."payment_status",
    "up"."created_at" AS "registration_date",
    "up"."attendees",
    "up"."counts",
    "up"."is_waitlisted"
   FROM (("public"."profiles" "p"
     JOIN "public"."user_parties" "up" ON (("p"."id" = "up"."user_id")))
     JOIN "public"."events" "e" ON (("up"."event_id" = "e"."id")));

ALTER VIEW "public"."user_event_history" OWNER TO "postgres";

COMMENT ON VIEW "public"."user_event_history" IS 'Admin view for drilling down into user participation history';

ALTER TABLE ONLY "public"."app_feedback"
    ADD CONSTRAINT "app_feedback_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_email_key" UNIQUE ("email");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."registration_edits"
    ADD CONSTRAINT "registration_edits_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_parties"
    ADD CONSTRAINT "user_parties_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_parties"
    ADD CONSTRAINT "user_parties_user_id_event_id_key" UNIQUE ("user_id", "event_id");

CREATE INDEX "idx_app_feedback_created_at" ON "public"."app_feedback" USING "btree" ("created_at");

CREATE INDEX "idx_app_feedback_is_resolved" ON "public"."app_feedback" USING "btree" ("is_resolved");

CREATE INDEX "idx_app_feedback_user_id" ON "public"."app_feedback" USING "btree" ("user_id");

CREATE INDEX "idx_events_is_active" ON "public"."events" USING "btree" ("is_active");

CREATE INDEX "idx_events_reg_start_date" ON "public"."events" USING "btree" ("reg_start_date");

CREATE INDEX "idx_events_status" ON "public"."events" USING "btree" ("status");

CREATE INDEX "idx_profiles_email" ON "public"."profiles" USING "btree" ("email");

CREATE INDEX "idx_profiles_is_admin" ON "public"."profiles" USING "btree" ("is_admin");

CREATE INDEX "idx_user_parties_event_id" ON "public"."user_parties" USING "btree" ("event_id");

CREATE INDEX "idx_user_parties_is_waitlisted" ON "public"."user_parties" USING "btree" ("is_waitlisted");

CREATE INDEX "idx_user_parties_payment_status" ON "public"."user_parties" USING "btree" ("payment_status");

CREATE INDEX "idx_user_parties_user_id" ON "public"."user_parties" USING "btree" ("user_id");

CREATE UNIQUE INDEX "only_one_active_event" ON "public"."events" USING "btree" ("is_active") WHERE ("is_active" = true);

COMMENT ON INDEX "public"."only_one_active_event" IS 'Ensures no two events can ever be active at the same time';

CREATE OR REPLACE TRIGGER "prevent_event_delete" BEFORE DELETE ON "public"."events" FOR EACH ROW EXECUTE FUNCTION "public"."prevent_event_deletion"();

CREATE OR REPLACE TRIGGER "trg_enforce_capacity_and_waitlist" BEFORE INSERT OR UPDATE OF "attendees", "status" ON "public"."user_parties" FOR EACH ROW EXECUTE FUNCTION "public"."enforce_capacity_and_waitlist"();

CREATE OR REPLACE TRIGGER "trg_increment_edit_count" BEFORE UPDATE ON "public"."user_parties" FOR EACH ROW EXECUTE FUNCTION "public"."increment_edit_count"();

CREATE OR REPLACE TRIGGER "trg_log_registration_edit" AFTER UPDATE ON "public"."user_parties" FOR EACH ROW EXECUTE FUNCTION "public"."log_registration_edit"();

CREATE OR REPLACE TRIGGER "trg_prevent_self_privilege_escalation" BEFORE UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."prevent_self_privilege_escalation"();

CREATE OR REPLACE TRIGGER "trg_protect_root_admin" BEFORE UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."protect_root_admin"();

CREATE OR REPLACE TRIGGER "update_counts" BEFORE INSERT OR UPDATE OF "attendees" ON "public"."user_parties" FOR EACH ROW EXECUTE FUNCTION "public"."update_attendee_counts"();

ALTER TABLE ONLY "public"."app_feedback"
    ADD CONSTRAINT "app_feedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."registration_edits"
    ADD CONSTRAINT "registration_edits_edited_by_fkey" FOREIGN KEY ("edited_by") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."registration_edits"
    ADD CONSTRAINT "registration_edits_registration_id_fkey" FOREIGN KEY ("registration_id") REFERENCES "public"."user_parties"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_parties"
    ADD CONSTRAINT "user_parties_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_parties"
    ADD CONSTRAINT "user_parties_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

CREATE POLICY "App Feedback: Admins can delete feedback" ON "public"."app_feedback" FOR DELETE USING ("public"."is_admin"());

CREATE POLICY "App Feedback: Users can insert own feedback" ON "public"."app_feedback" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "App Feedback: Users can read own feedback" ON "public"."app_feedback" FOR SELECT USING ((("auth"."uid"() = "user_id") OR "public"."is_admin"()));

CREATE POLICY "App Feedback: Users can update own feedback" ON "public"."app_feedback" FOR UPDATE USING ((("auth"."uid"() = "user_id") OR "public"."is_admin"())) WITH CHECK ((("auth"."uid"() = "user_id") OR "public"."is_admin"()));

CREATE POLICY "Events: Admin full access" ON "public"."events" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());

CREATE POLICY "Events: Public read active/archived" ON "public"."events" FOR SELECT USING ((("status" = ANY (ARRAY['ACTIVE'::"text", 'ARCHIVED'::"text"])) OR "public"."is_admin"()));

CREATE POLICY "Profiles: Admins can insert profiles" ON "public"."profiles" FOR INSERT WITH CHECK ((("auth"."uid"() = "id") OR "public"."is_admin"()));

CREATE POLICY "Profiles: User can insert own profile" ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));

CREATE POLICY "Profiles: User can read own profile" ON "public"."profiles" FOR SELECT USING ((("auth"."uid"() = "id") OR "public"."is_admin"()));

CREATE POLICY "Profiles: User can update own profile" ON "public"."profiles" FOR UPDATE USING ((("auth"."uid"() = "id") OR "public"."is_admin"())) WITH CHECK ((("auth"."uid"() = "id") OR "public"."is_admin"()));

CREATE POLICY "Registration Edits: System can insert edit records" ON "public"."registration_edits" FOR INSERT WITH CHECK ((("edited_by" = "auth"."uid"()) OR "public"."is_admin"()));

CREATE POLICY "Registration Edits: Users can see their own edit history" ON "public"."registration_edits" FOR SELECT USING ((("edited_by" = "auth"."uid"()) OR "public"."is_admin"()));

CREATE POLICY "User Parties: User can create own registrations" ON "public"."user_parties" FOR INSERT WITH CHECK ((("auth"."uid"() = "user_id") OR "public"."is_admin"()));

CREATE POLICY "User Parties: User can delete own registrations" ON "public"."user_parties" FOR DELETE USING ((("auth"."uid"() = "user_id") OR "public"."is_admin"()));

CREATE POLICY "User Parties: User can read own registrations" ON "public"."user_parties" FOR SELECT USING ((("auth"."uid"() = "user_id") OR "public"."is_admin"()));

CREATE POLICY "User Parties: User can update own registrations" ON "public"."user_parties" FOR UPDATE USING (((("auth"."uid"() = "user_id") AND ("status" = ANY (ARRAY['Enregistré'::"text", 'En attente'::"text"]))) OR "public"."is_admin"())) WITH CHECK (((("auth"."uid"() = "user_id") AND ("status" = ANY (ARRAY['Enregistré'::"text", 'En attente'::"text"]))) OR "public"."is_admin"()));

ALTER TABLE "public"."app_feedback" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."events" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."registration_edits" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_parties" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT ALL ON SCHEMA "public" TO "anon";
GRANT ALL ON SCHEMA "public" TO "authenticated";
GRANT ALL ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."admin_set_is_admin"("target_user_id" "uuid", "new_is_admin" boolean) TO "authenticated";

GRANT ALL ON FUNCTION "public"."enforce_capacity_and_waitlist"() TO "authenticated";

GRANT ALL ON TABLE "public"."app_feedback" TO "authenticated";

GRANT SELECT ON TABLE "public"."events" TO "anon";
GRANT ALL ON TABLE "public"."events" TO "authenticated";

GRANT ALL ON TABLE "public"."profiles" TO "authenticated";

GRANT ALL ON TABLE "public"."registration_edits" TO "authenticated";

GRANT ALL ON TABLE "public"."user_parties" TO "authenticated";

GRANT SELECT ON TABLE "public"."user_event_history" TO "authenticated";


-- Not captured by the dump (auth schema is excluded), but present in production.
CREATE OR REPLACE TRIGGER "on_auth_user_created" AFTER INSERT ON "auth"."users" FOR EACH ROW EXECUTE FUNCTION "public"."handle_new_user"();
